import { Link } from "react-router-dom";
import {
  Sparkles,
  ArrowRight,
  Image,
  Shirt,
} from "lucide-react";

import "../Resources.css";
import HeroWorkflowSlideshow from "../../../components/resources/HeroWorkflowSlideshow";


export default function AIHeroGuidePage() {
  return (
    <div className="resources-page">

      {/* ======================================================
          HERO
      ======================================================= */}

      <section className="resource-hero">

        <div className="resource-badge">
          <Sparkles size={16} />
          GUIDE
        </div>

        <h1>AI Hero Guide</h1>

        <p>
          Learn how to generate clean, professional AI fashion
          model images that become the foundation for
          Lookbooks, Campaigns, Product Images and AI Reels.
        </p>

      </section>

      {/* ======================================================
          INTRODUCTION
      ======================================================= */}

      <section className="resource-section">

        <div className="welcome-card">

          <h2>What is an AI Hero?</h2>

          <p>
            An AI Hero is the primary fashion model image
            generated by MagicReel using your garment
            photographs. Every downstream feature—including
            Lookbooks, AI Reels and Campaign generation—starts
            from a high-quality Hero image.
          </p>

          <ul className="welcome-list">

            <li>Create realistic fashion model photographs.</li>

            <li>Support front and back garment generation.</li>

            <li>Maintain garment details and proportions.</li>

            <li>Serve as the foundation for all AI assets.</li>

          </ul>

        </div>

      </section>

      {/* ======================================================
          WORKFLOW
      ======================================================= */}

      <section className="resource-section hero-workflow-section">

        <div className="section-header">

          <h2>AI Hero Workflow</h2>

          <p>
            Create your AI Hero in 7 simple steps.
            Follow the visual walkthrough below to go from
            garment selection to your finished Hero images.
          </p>

        </div>

        <HeroWorkflowSlideshow
          steps={[
            {
              number: 1,
              title: "Select Gender",
              narration:
                "Start by selecting the gender that matches your garment and the fashion presentation you want to create.",
              image:
                new URL("../../../assets/docs/hero/hero-step-1.png", import.meta.url).href,
              alt: "Step 1: Select Gender in MagicReel",
            },
            {
              number: 2,
              title: "Select Garment",
              narration:
                "Select the garment category that matches your product. Browse the available garment categories before making your selection.",
              image:
                new URL("../../../assets/docs/hero/hero-step-2.png", import.meta.url).href,
              alt: "Step 2: Select Garment category in MagicReel",
            },
            {
              number: 3,
              title: "Select Garment Detail",
              narration:
                "Select the garment detail pills that accurately describe your product. These selections help MagicReel understand the garment correctly.",
              image:
                new URL("../../../assets/docs/hero/hero-step-3.png", import.meta.url).href,
              alt: "Step 3: Select garment detail pills in MagicReel",
            },
            {
              number: 4,
              title: "Upload Your Garment",
              narration:
                "Upload the Front garment image. A Back image is optional at this stage.",
              image:
                new URL("../../../assets/docs/hero/hero-step-4.png", import.meta.url).href,
              alt: "Step 4: Upload Front and Back garment images",
            },
            {
              number: 5,
              title: "Confirm Your Garment",
              narration:
                "Front is required. Back is optional but required for Lookbook Back Pose and 360° Reel.",
              image:
                new URL("../../../assets/docs/hero/hero-step-5.png", import.meta.url).href,
              alt: "Step 5: Confirm uploaded garment images before generating",
            },
            {
              number: 6,
              title: "Select Your Muse",
              narration:
                "Choose the Muse that best matches the look and presentation you want for your AI Hero.",
              image:
                new URL("../../../assets/docs/hero/hero-step-6.png", import.meta.url).href,
              alt: "Step 6: Select a Muse in MagicReel",
            },
            {
              number: 7,
              title: "Generate Your Hero",
              narration:
                "Click Generate Hero. MagicReel processes your selections and displays the generated Hero images in the result area.",
              image:
                new URL("../../../assets/docs/hero/hero-step-7.png", import.meta.url).href,
              alt: "Step 7: Generate Hero and view the resulting Hero images",
            },
          ]}
        />

      </section>

      {/* ======================================================
          IMAGE REQUIREMENTS
      ======================================================= */}

      <section className="resource-section">

        <div className="section-header">

          <h2>Garment Image Best Practices</h2>

          <p>
            The quality of your uploaded garment directly affects
            the quality of the generated AI Hero.
          </p>

        </div>

        <div className="learning-grid">

          <div className="learn-card">

            <Image size={26} />

            <h3>Use High Resolution Images</h3>

            <p>
              Upload clear, sharp garment photos with sufficient
              resolution. Avoid blurry or compressed images.
            </p>

          </div>

          <div className="learn-card">

            <Shirt size={26} />

            <h3>Flat & Well Aligned</h3>

            <p>
              Keep the garment flat with minimal folds so the AI
              can accurately understand its shape and structure.
            </p>

          </div>

          <div className="learn-card">

            <Sparkles size={26} />

            <h3>Good Lighting</h3>

            <p>
              Use evenly lit photographs without strong shadows
              or overexposed areas.
            </p>

          </div>

        </div>

      </section>

      {/* ======================================================
          TIPS
      ======================================================= */}

      <section className="resource-section">

        <div className="welcome-card">

          <h2>Tips for Better AI Heroes</h2>

          <ul className="welcome-list">

            <li>Use a clean background behind the garment.</li>

            <li>Capture the entire garment without cropping.</li>

            <li>Avoid mannequin arms or unnecessary accessories.</li>

            <li>Ensure colors closely match the real garment.</li>

            <li>Generate both Front and Back Heroes whenever possible.</li>

          </ul>

        </div>

      </section>

      {/* ======================================================
          NEXT STEP
      ======================================================= */}

      <section className="resource-section">

        <div className="section-header">

          <h2>Continue Learning</h2>

          <p>
            Once your AI Hero is ready, the next step is creating
            a professional fashion Lookbook.
          </p>

        </div>

        <div className="next-guide-grid">

          <Link
            to="/docs/lookbook"
            className="guide-card"
          >

            <ArrowRight size={24} />

            <h3>Next: Lookbook Guide</h3>

            <p>
              Learn how to transform your AI Hero into premium
              editorial lookbooks for e-commerce and marketing.
            </p>

          </Link>

        </div>

      </section>

            {/* ======================================================
          SUMMARY
      ======================================================= */}

      <section className="resource-section">

        <div className="welcome-card">

          <h2>Summary</h2>

          <p>
            High-quality garment photographs are the foundation
            of great AI Heroes. Following the recommended
            workflow and image guidelines will help MagicReel
            generate realistic fashion model images that produce
            better Lookbooks, Campaigns and AI Reels.
          </p>

        </div>

      </section>

    </div>
  );
}