import { Link } from "react-router-dom";
import {
  Sparkles,
  ArrowRight,
  Image,
  Shirt,
} from "lucide-react";

import "../Resources.css";

export default function AIHeroGuidePage() {
  return (
    <div className="resources-page">

      {/* ======================================================
          HERO
      ======================================================= */}

      <section className="resource-hero">

        <div className="resource-badge">
          <Sparkles size={16} />
          GUIDE
        </div>

        <h1>AI Hero Guide</h1>

        <p>
          Learn how to generate clean, professional AI fashion
          model images that become the foundation for
          Lookbooks, Campaigns, Product Images and AI Reels.
        </p>

      </section>

      {/* ======================================================
          INTRODUCTION
      ======================================================= */}

      <section className="resource-section">

        <div className="welcome-card">

          <h2>What is an AI Hero?</h2>

          <p>
            An AI Hero is the primary fashion model image
            generated by MagicReel using your garment
            photographs. Every downstream feature—including
            Lookbooks, AI Reels and Campaign generation—starts
            from a high-quality Hero image.
          </p>

          <ul className="welcome-list">

            <li>Create realistic fashion model photographs.</li>

            <li>Support front and back garment generation.</li>

            <li>Maintain garment details and proportions.</li>

            <li>Serve as the foundation for all AI assets.</li>

          </ul>

        </div>

      </section>

      {/* ======================================================
          WORKFLOW
      ======================================================= */}

      <section className="resource-section">

        <div className="section-header">

          <h2>AI Hero Workflow</h2>

          <p>
            Follow these recommended steps to consistently
            generate high-quality Hero images.
          </p>

        </div>

        <div className="quick-start-grid">

          <div className="guide-card">

            <div className="step-number">1</div>

            <h3>Upload Garment</h3>

            <p>
              Upload a clean front garment image with good
              lighting and minimal wrinkles.
            </p>

          </div>

          <div className="guide-card">

            <div className="step-number">2</div>

            <h3>Select Muse</h3>

            <p>
              Choose the AI model that best matches your
              campaign requirements.
            </p>

          </div>

          <div className="guide-card">

            <div className="step-number">3</div>

            <h3>Generate Hero</h3>

            <p>
              MagicReel creates a realistic fashion model while
              preserving garment appearance and fit.
            </p>

          </div>

        </div>

      </section>

            {/* ======================================================
          IMAGE REQUIREMENTS
      ======================================================= */}

      <section className="resource-section">

        <div className="section-header">

          <h2>Garment Image Best Practices</h2>

          <p>
            The quality of your uploaded garment directly affects
            the quality of the generated AI Hero.
          </p>

        </div>

        <div className="learning-grid">

          <div className="learn-card">

            <Image size={26} />

            <h3>Use High Resolution Images</h3>

            <p>
              Upload clear, sharp garment photos with sufficient
              resolution. Avoid blurry or compressed images.
            </p>

          </div>

          <div className="learn-card">

            <Shirt size={26} />

            <h3>Flat & Well Aligned</h3>

            <p>
              Keep the garment flat with minimal folds so the AI
              can accurately understand its shape and structure.
            </p>

          </div>

          <div className="learn-card">

            <Sparkles size={26} />

            <h3>Good Lighting</h3>

            <p>
              Use evenly lit photographs without strong shadows
              or overexposed areas.
            </p>

          </div>

        </div>

      </section>

      {/* ======================================================
          TIPS
      ======================================================= */}

      <section className="resource-section">

        <div className="welcome-card">

          <h2>Tips for Better AI Heroes</h2>

          <ul className="welcome-list">

            <li>Use a clean background behind the garment.</li>

            <li>Capture the entire garment without cropping.</li>

            <li>Avoid mannequin arms or unnecessary accessories.</li>

            <li>Ensure colors closely match the real garment.</li>

            <li>Generate both Front and Back Heroes whenever possible.</li>

          </ul>

        </div>

      </section>

      {/* ======================================================
          NEXT STEP
      ======================================================= */}

      <section className="resource-section">

        <div className="section-header">

          <h2>Continue Learning</h2>

          <p>
            Once your AI Hero is ready, the next step is creating
            a professional fashion Lookbook.
          </p>

        </div>

        <div className="next-guide-grid">

          <Link
            to="/docs/lookbook"
            className="guide-card"
          >

            <ArrowRight size={24} />

            <h3>Next: Lookbook Guide</h3>

            <p>
              Learn how to transform your AI Hero into premium
              editorial lookbooks for e-commerce and marketing.
            </p>

          </Link>

        </div>

      </section>

            {/* ======================================================
          SUMMARY
      ======================================================= */}

      <section className="resource-section">

        <div className="welcome-card">

          <h2>Summary</h2>

          <p>
            High-quality garment photographs are the foundation
            of great AI Heroes. Following the recommended
            workflow and image guidelines will help MagicReel
            generate realistic fashion model images that produce
            better Lookbooks, Campaigns and AI Reels.
          </p>

        </div>

      </section>

    </div>
  );
}