import { useEffect, useMemo, useRef, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { API_BASE } from "../../../config/api";
import "./ecomOutputV1.css";

type Pose = { poseId: string; imageUrl?: string };
const POLL_MS = 4000;
const MAX_POLLS = 120;
const EXPECTED_ASSETS = 6;
const labelForPose = (poseId: string) => { const id = poseId.toLowerCase(); if (id === "front" || id === "hero") return "FRONT"; if (id === "back") return "BACK"; const match = id.match(/^pose_(\d+)$/); return match ? `POSE ${match[1]}` : poseId.replace(/_/g, " ").toUpperCase(); };
export default function EcomOutputV1Page() {
  const { id } = useParams(); const navigate = useNavigate(); const [loading,setLoading]=useState(true); const [poses,setPoses]=useState<Pose[]>([]); const [aspectRatio,setAspectRatio]=useState("2:3"); const [shareId,setShareId]=useState<string|null>(null); const [error,setError]=useState<string|null>(null); const [selectedImage,setSelectedImage]=useState<string|null>(null); const [exporting,setExporting]=useState(false); const [generatingReel,setGeneratingReel]=useState(false); const [copying,setCopying]=useState(false); const [polls,setPolls]=useState(0); const pollCountRef=useRef(0);
  useEffect(()=>{ if(!id){setLoading(false);setError("Lookbook run not found");return;} let cancelled=false; let timer:ReturnType<typeof setTimeout>|undefined; pollCountRef.current=0; const load=async()=>{try{const token=localStorage.getItem("token");const res=await fetch(`${API_BASE}/api/p2m/lookbook-v1/status/${id}`,{headers:{Authorization:`Bearer ${token}`}});const data=await res.json();if(cancelled)return;if(!res.ok)throw new Error(data?.error||"Failed to load Lookbook");const nextPoses:Pose[]=(data?.poses||[]).map((p:any)=>({poseId:String(p.poseId||"").toLowerCase(),imageUrl:p.imageUrl||p.resultImageUrl||undefined}));setPoses(nextPoses);if(nextPoses[0]?.imageUrl)setSelectedImage(current=>current||nextPoses[0].imageUrl!);if(data?.aspectRatio)setAspectRatio(String(data.aspectRatio));if(data?.shareId)setShareId(String(data.shareId));if(data?.status==="completed"){setLoading(false);return;}if(data?.status==="failed"){setLoading(false);setError("Lookbook generation failed");return;}const nextPolls=pollCountRef.current+1;pollCountRef.current=nextPolls;setPolls(nextPolls);if(nextPolls>=MAX_POLLS){setLoading(false);setError("Lookbook generation timed out. Please try again.");return;}timer=setTimeout(load,POLL_MS);}catch(err:any){if(cancelled)return;const nextPolls=pollCountRef.current+1;pollCountRef.current=nextPolls;setPolls(nextPolls);if(nextPolls>=MAX_POLLS){setLoading(false);setError(err?.message||"Unable to retrieve Lookbook results.");return;}timer=setTimeout(load,POLL_MS);}};load();return()=>{cancelled=true;if(timer)clearTimeout(timer);};},[id]);
  const imagePoses=useMemo(()=>poses.filter(p=>p.imageUrl),[poses]); const selectedPose=useMemo(()=>imagePoses.find(p=>p.imageUrl===selectedImage),[imagePoses,selectedImage]);
  const handleExport=async()=>{if(!imagePoses.length)return;setExporting(true);try{const token=localStorage.getItem("token");const res=await fetch(`${API_BASE}/api/p2m/lookbook-v1/export`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({images:imagePoses.map(p=>p.imageUrl).filter(Boolean)})});if(!res.ok)throw new Error("Export failed");const blob=await res.blob();const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="magicreel-lookbook.zip";document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);}catch(err){console.error("Lookbook export error",err);alert("Download failed");}finally{setExporting(false);}};
  const handleCopyLink=async()=>{if(!shareId)return;setCopying(true);try{await navigator.clipboard.writeText(`${window.location.origin}/share/${shareId}`);}catch(err){console.error("Lookbook link copy error",err);alert("Unable to copy link");}finally{setCopying(false);}};
  const handleCarouselReel=async()=>{if(!id)return;setGeneratingReel(true);try{const response=await fetch(`${API_BASE}/api/p2m/reel/carousel`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({lookbookId:id})});const data=await response.json();const reelVideoUrl=data?.videoUrl||data?.reelVideoUrl;if(!response.ok||!data?.success||!reelVideoUrl)throw new Error(data?.error||"Reel generation failed");window.open(reelVideoUrl,"_blank");}catch(err:any){console.error("Carousel Reel error",err);alert(err?.message||"Failed to generate Carousel Reel");}finally{setGeneratingReel(false);}};
  const handlePublish=()=>{if(!selectedImage)return;navigate(`/publish?assetUrl=${encodeURIComponent(selectedImage)}&assetType=image`);};
  if(loading){const progress=Math.min(100,Math.round((imagePoses.length/EXPECTED_ASSETS)*100));return <div className="lookbook-v1-loading"><div className="lookbook-v1-loading-card"><div className="lookbook-v1-eyebrow">MAGICREEL AI STUDIO</div><h1>Creating Your Lookbook</h1><p>Creating 2 Hero images + 4 commercial Lookbook poses, including one close-in product detail.</p><div className="lookbook-v1-progress-head"><span>Assets completed</span><strong>{imagePoses.length} / {EXPECTED_ASSETS}</strong></div><div className="lookbook-v1-progress-track"><div className="lookbook-v1-progress-bar" style={{width:`${progress}%`}}/></div><div className="lookbook-v1-poll">Checking generation status · {polls}</div><p className="lookbook-v1-hint">Please keep this tab open. Images will appear automatically when ready.</p></div></div>;}
  return <div className="lookbook-v1-page"><header className="lookbook-v1-header"><div className="lookbook-v1-title">MagicReel Lookbook · {aspectRatio}</div><div className="lookbook-v1-actions"><button className="lookbook-v1-action" onClick={handleCarouselReel} disabled={generatingReel||imagePoses.length<EXPECTED_ASSETS}>{generatingReel?"Creating Reel...":"Carousel Reel"}</button><button className="lookbook-v1-action" onClick={handleCopyLink} disabled={!shareId||copying}>{copying?"Copied ✓":"Copy link"}</button><button className="lookbook-v1-action" onClick={handlePublish} disabled={!selectedImage}>Publish</button><button className="lookbook-v1-action lookbook-v1-download" onClick={handleExport} disabled={exporting||!imagePoses.length}>{exporting?"Preparing...":"Download ZIP"}</button></div></header><main className="lookbook-v1-main"><section className="lookbook-v1-preview-column"><div className="lookbook-v1-section-label">LOOKBOOK PREVIEW · {aspectRatio}</div><div className="lookbook-v1-preview-frame">{selectedImage&&<img src={selectedImage} alt="Selected Lookbook"/>}</div>{selectedPose&&<div className="lookbook-v1-selected-label">{labelForPose(selectedPose.poseId)}</div>}</section><section className="lookbook-v1-gallery">{error&&<div className="lookbook-v1-error">{error}</div>}<div className="lookbook-v1-gallery-head"><div><div className="lookbook-v1-gallery-title">{imagePoses.length} Images Generated</div><div className="lookbook-v1-gallery-subtitle">2 Hero references + 4 Lookbook poses</div></div></div><div className="lookbook-v1-grid">{imagePoses.map((pose,index)=><button key={`${pose.poseId}-${index}`} type="button" className={`lookbook-v1-thumb ${selectedImage===pose.imageUrl?"selected":""}`} onClick={()=>pose.imageUrl&&setSelectedImage(pose.imageUrl)}><img src={pose.imageUrl||""} alt={labelForPose(pose.poseId)}/><span>{labelForPose(pose.poseId)}</span></button>)}</div></section></main></div>;
}
