import { useEffect,useState } from "react";
import { useNavigate,useParams } from "react-router-dom";
import { API_BASE } from "../../../config/api";
import "./ecomOutputV1.css";

type Pose={poseId:string;imageUrl?:string};
export default function EcomLookbookV1OutputPage(){
 const {id}=useParams(); const navigate=useNavigate(); const [poses,setPoses]=useState<Pose[]>([]); const [selected,setSelected]=useState(0); const [aspect,setAspect]=useState("2:3"); const [shareId,setShareId]=useState<string|null>(null); const [loading,setLoading]=useState(true); const [reel,setReel]=useState(false); const [downloading,setDownloading]=useState(false);
 useEffect(()=>{let cancelled=false; let timer:ReturnType<typeof setTimeout>|undefined; const load=async()=>{try{const token=localStorage.getItem("token");const r=await fetch(`${API_BASE}/api/p2m/lookbook-v1/status/${id}`,{headers:{Authorization:`Bearer ${token}`}});const d=await r.json();if(cancelled)return;const p=(d.poses||[]).map((x:any)=>({poseId:String(x.poseId||"").toLowerCase(),imageUrl:x.imageUrl||x.resultImageUrl})).filter((x:Pose)=>x.imageUrl).slice(0,6);setPoses(p);if(d.aspectRatio)setAspect(String(d.aspectRatio));if(d.shareId)setShareId(String(d.shareId));if(d.status==="completed")setLoading(false);else timer=setTimeout(load,3000);}catch(e){if(!cancelled)setLoading(false);}};load();return()=>{cancelled=true;if(timer)clearTimeout(timer);};},[id]);
 const generateReel=async()=>{setReel(true);try{const r=await fetch(`${API_BASE}/api/p2m/reel/carousel`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({lookbookId:id})});const d=await r.json();if(!r.ok||!d.success||!d.reelId)throw new Error(d.error||"Reel generation failed");navigate(`/reel/${d.reelId}`);}catch(e:any){alert(e?.message||"Reel generation failed");}finally{setReel(false);}};
 const downloadZip=async()=>{setDownloading(true);try{const token=localStorage.getItem("token");const r=await fetch(`${API_BASE}/api/p2m/lookbook-v1/export`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({images:poses.map(p=>p.imageUrl).filter(Boolean)})});if(!r.ok)throw new Error("Download failed");const b=await r.blob();const u=URL.createObjectURL(b);const a=document.createElement("a");a.href=u;a.download="magicreel-lookbook.zip";document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(u);}catch(e){alert("Download failed");}finally{setDownloading(false);}};
 if(loading)return <div className="lookbook-v1-loading"><div className="lookbook-v1-loading-card"><div className="lookbook-v1-eyebrow">MAGICREEL AI STUDIO</div><h1>Loading Your Lookbook</h1><p>Preparing your six-image fashion pack.</p></div></div>;
 const copy=async()=>{if(shareId)await navigator.clipboard.writeText(`${window.location.origin}/share/${shareId}`);};
 return <div className="lookbook-v1-page"><header className="lookbook-v1-header"><div className="lookbook-v1-title">MagicReel Lookbook · {aspect}</div><div className="lookbook-v1-actions"><button className="lookbook-v1-action" onClick={generateReel} disabled={reel}>{reel?"Creating Reel...":"Carousel Reel"}</button><button className="lookbook-v1-action" onClick={copy} disabled={!shareId}>Copy link</button><button className="lookbook-v1-action" onClick={()=>navigate(`/publish?assetUrl=${encodeURIComponent(poses[selected]?.imageUrl||"")}&assetType=image`)}>Publish</button><button className="lookbook-v1-action lookbook-v1-download" onClick={downloadZip} disabled={downloading}>{downloading?"Preparing...":"Download ZIP"}</button></div></header><main className="lookbook-v1-main"><section className="lookbook-v1-preview-column"><div className="lookbook-v1-section-label">LOOKBOOK PREVIEW · {aspect}</div><div className="lookbook-v1-preview-frame">{poses[selected]?.imageUrl&&<img src={poses[selected].imageUrl} alt="Selected Lookbook"/>}</div></section><section className="lookbook-v1-gallery"><div className="lookbook-v1-gallery-head"><div><div className="lookbook-v1-gallery-title">{poses.length} Images Generated</div><div className="lookbook-v1-gallery-subtitle">2 Hero references + 4 Lookbook poses</div></div></div><div className="lookbook-v1-grid">{poses.map((p,i)=><button key={`${p.poseId}-${i}`} className={`lookbook-v1-thumb ${i===selected?"selected":""}`} onClick={()=>setSelected(i)}><img src={p.imageUrl||""} alt={p.poseId}/><span>{p.poseId}</span></button>)}</div></section></main></div>;
}
